name: flutter_recorder_example
description: "Demonstrates how to use the flutter_recorder plugin."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  flutter_recorder:
    path: ../

  cupertino_icons: ^1.0.8
  open_filex: ^4.5.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
