name: flutter_recorder
description: >-
  A low-level audio recorder plugin which uses miniaudio as
  backend and supporting all the platforms. It can detect
  volume level and silence and save to WAV audio file. Audio
  wave and FFT data can be get in real-time as for the volume level.
version: 0.9.1
issue_tracker: https://github.com/alnitak/flutter_recorder/issues
homepage: https://github.com/alnitak/flutter_recorder
maintainer: Marco Bavagnoli (@lildeimos)
platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
topics:
  - audio
  - recorder
  - visualizer

screenshots:
  - description: "recording"
    path: images/recording.jpg

environment:
  sdk: ^3.5.1
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  meta: ^1.12.0
  plugin_platform_interface: ^2.0.2
  web: ^1.1.0

dev_dependencies:
  ffigen: ^13.0.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      web:
        default_package: true

  assets:
    # These assets are only needed for the web platform.
    # Waiting for https://github.com/flutter/flutter/issues/65065 and
    # https://github.com/flutter/flutter/issues/8230 to be addressed.
    # to make a conditional build.
    - web/worker.dart.js
    - web/libflutter_recorder_plugin.js
    - web/libflutter_recorder_plugin.wasm
