name: flutter_recorder
description: "A new Flutter FFI plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.1
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  meta: ^1.12.0
  plugin_platform_interface: ^2.0.2
  web: ^1.1.0

dev_dependencies:
  ffigen: ^13.0.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      web:
        default_package: true

  assets:
    # These assets are only needed for the web platform.
    # Waiting for https://github.com/flutter/flutter/issues/65065 and
    # https://github.com/flutter/flutter/issues/8230 to be addressed.
    # to make a conditional build.
    - web/worker.dart.js
    - web/libflutter_recorder_plugin.js
    - web/libflutter_recorder_plugin.wasm
